## Minimal GoNeovim configuration (bundled via wrapper-manager)
[Editor]
RestoreWindowGeometry = true
StartMaximizedWindow = true
FontSize = 14
SmoothScroll = true
[Cursor]
SmoothMove = true
[MiniMap]
visible = true
